services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - linktree

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - linktree

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      - redis
      - mongo
    networks:
      - linktree

  worker:
    build: .
    command: rq worker
    mem_limit: 1024m
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - mongo
    restart: always
    networks:
      - linktree

networks:
  linktree:
