services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - linktree

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - linktree

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - mongo
    networks:
      - linktree

  keyword_worker:
    build: .
    command: rq worker keyword
    mem_limit: 1024m
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - mongo
    networks:
      - linktree

  crawl_worker:
    build: .
    command: rq worker crawl
    mem_limit: 1024m
    deploy:
      replicas: 25
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - mongo
    networks:
      - linktree

networks:
  linktree:
